highlighter: pygments

name: Two Or More

description: Musings and rambling, and some code.

url: http://twoormore.eu

defaults:
  -
    scope:
      path: ""
    values:
      layout: "master"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      
encoding: utf-8